name: Test Using Elvish as Default

on:
  push:
    branches: [main]

defaults:
  run:
    shell: elvish

jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
    - uses: ${{ github.repository }}@main
    - name: Run with Elvish
      shell: elvish {0}
      run: |
        echo This is Elvish $version
