name: Test

on:
  push:
    branches: [main]

jobs:
  test_action:
    name: Test Action
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        elvish-version: [0.18.0, HEAD]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: ${{ github.repository }}@main
      with:
        elvish-version: ${{ matrix.elvish-version }}
    - name: Run with Elvish
      shell: elvish {0}
      run: |
        echo This is Elvish $version
